### Register
POST http://localhost:8000/api/register 
Content-Type: application/json

{
    "name": "test",
    "email": "test@email.com",
    "password": "test"
}

### Login
POST http://localhost:8000/api/login   
Content-Type: application/json

{
    "email": "test@email.com",
    "password": "test"
}

// Survey
### Get all survey for user
GET http://localhost:8000/api/survey

### Get survey of user
GET http://localhost:8000/api/survey/5ffa283900b687e80033b003

### Create survey
POST http://localhost:8000/api/survey/
Content-Type: application/json

{
    "name": "Survey 1",
    "description": "Here is a survey"
}


### Update survey
POST http://localhost:8000/api/survey/:id

### Delete survey
DELETE http://localhost:8000/api/survey/:id